### ISSUE TITLE
bundle.yaml instead of _layout

### ISSUE THREAD

**Issue by Denver-22** [apex-project/pyApex#11]
Hi!
In pyRevit version 4.8, bundle.yaml is used instead of _layout to sort items in a panel.
I see that the .stack directories already match the new rule. Please update these files as well.
I am attaching new files based on the original _layout.
[bundle.yaml_(2).zip](https://github.com/apex-project/pyApex/files/9121514/bundle.yaml_.2.zip)

**Comment by melnikovalex** [comment]
Hi @Denver-22

Thank you for taking care 👍 and sorry for the delay with response. 
I've just merged your fixes

As you might notice, there is not happening a lot in the repository. The last changes were renaming .stack3 to .stack Merged from Ehsan's PR #9

But it is anyway very nice to see people involved and using those scripts. 
So please feel free to write any issues or suggestions. 
Next time I will try to be faster with answer 😁 

Hope it has helped. Have fun with pyRevit!
