### ISSUE TITLE
pyApex launching error

### ISSUE THREAD

**Issue by Alboundy** [apex-project/pyApex#5]
![error pyapex](https://user-images.githubusercontent.com/47317117/52202667-7c18ed00-286f-11e9-91ac-72247b13d380.png)

Hello Aleksey

I really like your work! 
Your tool is really usefull, specially the "copy VG filter" , what a great surprise when i found it ;). It saves a lot of time!
I like the "open views" button a lot too

I have an issue on Revit 2018, but in 2016 and 2019 too.
I can't use pyApex anymore, i get an error every time, on many function. I send a screenshot .
I try to disable, remove and reinstall the extension, nothing works.

Looking forward to reading from you soon again.

Bye

**Comment by melnikovalex** [comment]
Hi Alboundy! thank you for this issue. I wasn't able to implement all updates which came with pyRevit 4.6
This one should work after pyApex update
